### ISSUE TITLE
Password not generated when requirements set to "none"

### ISSUE THREAD

**Issue by jacmaes** [Toutouwai/PasswordGenerator#2]
When I set the password requirements in the password field to "none (disable all above)":
<img width="254" alt="requirements" src="https://user-images.githubusercontent.com/1206842/82737233-d45b5300-9d2f-11ea-9172-40c05a620010.png">

The password generation fails and the password preview is collapsed:
<img width="553" alt="password" src="https://user-images.githubusercontent.com/1206842/82737235-d7eeda00-9d2f-11ea-987d-c0ce73e2b488.png">

Note: no JS error in the console.

**Comment by Toutouwai** [comment]
Thanks for the report.

The generator needs to be told what kinds of characters should be used in the generated passwords. In v0.1.7 I've set a fallback to lowercase letter so that at least something is generated, but I recommend using "Password generator settings: overrides" in the module config if you aren't setting any requirements on the password field itself.
